### ISSUE TITLE
exampleProg.py does not work properly

### ISSUE THREAD

**Issue by alejandro-aragon** [ElsevierDev/elsapy#24] opened 2018-04-19 14:20 UTC
Hi everyone,

I'm trying to run the example as it's given, but I don't get the expected behavior while reading docs:

$ python exampleProg.py 
my_auth.full_name:  Paul John McGuiness
my_aff.name:  American Institute of Steel Construction
scp_doc.title:  Control of somatic tissue differentiation by the long non-coding RNA TINCR
pii_doc.title:  Establishing the fair allocation of international aviation carbon emission rights 
doi_doc.title:  Sensitive Sequencing Method for KRAS Mutation Detection by Pyrosequencing 
Load documents (Y/N)?
--> Y
Read docs for author failed.
Read docs for affiliation failed.
auth_srch has 13 results.
aff_srch has 25 results.
doc_srch has 184 results.

Perhaps I'm not using the latest version of the API because I installed it through pip? Thanks for the help.

**Comment by ale-de-vries** [comment] 2019-08-07 02:18
Apologies for the late reply, closing out all issues.

Duplicate of #37

**Closed by ale-de-vries** 2019-08-07 02:18 UTC
